# Generated by Django 5.2.10 on 2026-02-13 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview_pending', 'AI Interview Pending'), ('round1', 'Technical Round 1'), ('round2', 'Technical Round 2'), ('final', 'Final Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('ai_score', models.IntegerField(default=0)),
                ('ai_transcript', models.TextField(blank=True, help_text='Full text-based conversation log')),
                ('ai_behavioral_notes', models.TextField(blank=True, help_text='Insights on confidence, surroundings, etc.')),
                ('is_authentic', models.BooleanField(default=True, help_text='AI check for fake/real interaction')),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='recruiter.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ssc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intermediate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma separated skills')),
                ('interested_roles', models.CharField(blank=True, max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/')),
                ('profile_picture', models.ImageField(default='profiles/default_user.png', upload_to='profiles/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
