# Generated by Django 5.2.10 on 2026-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='interested_roles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
