# Generated by Django 5.2.10 on 2026-02-13 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(help_text='e.g. Software, Finance, Manufacturing', max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief about the company')),
                ('contact_email', models.EmailField(max_length=254)),
                ('company_logo', models.ImageField(default='logos/default_company.png', upload_to='logos/')),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eligibility_criteria', models.TextField(help_text='Education, year of passing, etc.')),
                ('required_skills', models.TextField(help_text='Comma separated skills')),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('deadline', models.DateTimeField()),
                ('location', models.CharField(default='Remote', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='recruiter.recruiterprofile')),
            ],
        ),
    ]
