# Generated by Django 5.2.10 on 2026-03-05 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='min_cgpa',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=4, validators=[django.core.validators.MinValueValidator(7.5)]),
        ),
    ]
